@host = {{localhost5000}}

@serverPath = {{host}}/server/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2MTYxOTMzOCwianRpIjoiZjg2NzM5OTQtNGFlNS00OWQ4LWI2NDktNGQxZGZjOWY3MTA0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFydmlfNTYyOTM2IiwibmJmIjoxNjYxNjE5MzM4fQ.xcKuUP3OIjrLhp0slXjJb94P98TbHdOXhlM8QNuOBGk


### 
GET  {{serverPath}}/pay
# Authorization: Bearer {{token}}

### 
POST  {{serverPath}}/payment/success


# {
#   "id": "order_KD1SGEDAcXhVy0",
#   "entity": "order",
#   "amount": 500,
#   "amount_paid": 0,
#   "amount_due": 500,
#   "currency": "INR",
#   "receipt": "order_rcptid_11",
#   "offer_id": null,
#   "status": "created",
#   "attempts": 0,
#   "notes": [],
#   "created_at": 1662119679
# }
